version bump 10 commits vim-youcompleteme-git

diff --git a/vim-youcompleteme-git/PKGBUILD b/vim-youcompleteme-git/PKGBUILD
--- a/vim-youcompleteme-git/PKGBUILD
+++ b/vim-youcompleteme-git/PKGBUILD
@@ -37,12 +37,12 @@ _neovim="$NEOVIM_YOUCOMPLETEME"
 #                                    Default PKGBUILD Configuration                                       #
 #=========================================================================================================#
 pkgname=vim-youcompleteme-git
-pkgver=r2439.75bf1738
+pkgver=r2449.0790dc99
 pkgver() {
 	cd "YouCompleteMe" || exit
 	printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
 }
-pkgrel=2
+pkgrel=1
 pkgdesc="A code-completion engine for Vim"
 arch=('any')
 url='https://github.com/Valloric/YouCompleteMe'
@@ -56,15 +56,19 @@ source=(
 'git+https://github.com/ross/requests-futures.git'  #ycm
 'git+https://github.com/Valloric/ycmd.git'          #ycm
 'git+https://github.com/kennethreitz/requests.git'  #ycmd
-'git+https://github.com/bottlepy/bottle.git'        #ycmd
+'git+https://github.com/kjd/idna.git'  #ycmd
+'git+https://github.com/certifi/python-certifi.git'  #ycmd
+'git+https://github.com/chardet/chardet.git'  #ycmd
+'git+https://github.com/urllib3/urllib3.git'  #ycmd
+'git+https://github.com/defnull/bottle.git'  #ycmd
 'git+https://github.com/slezica/python-frozendict.git'    #ycmd
 'git+https://github.com/PythonCharmers/python-future.git' #ycmd
 'git+https://github.com/davidhalter/jedi.git'             #jedi
 'git+https://github.com/davidhalter/parso.git'            #jedi
 'git+https://github.com/Pylons/waitress.git'              #ycmd,jediHTTP
-'git+https://github.com/Manishearth/godef.git'            #ycmd
+'git+https://github.com/micbou/regex.git'  #ycmd
 )
-sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')
+sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP')
 #=========================================================================================================#
 #=========================================================================================================#
 
@@ -76,7 +80,9 @@ sha256sums=('SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP' 'SKIP
 
 if [[ "$_gocode" == "y" ]]; then
 	# ycmd
-	source+=('git+https://github.com/nsf/gocode.git')
+	source+=('git+https://github.com/mdempsky/gocode.git')
+	source+=('git+https://github.com/rogpeppe/godef.git')
+	sha256sums+=('SKIP')
 	sha256sums+=('SKIP')
 	makedepends+=('go')
 fi
@@ -167,14 +173,12 @@ prepare() {
 
 	msg2 'Setting up Git submodules...'
 
-	local YouCompleteMe=("requests-futures" "ycmd")
+	local YouCompleteMe=("requests-futures" "ycmd" "python-futures")
+	local YouCompleteMeRequestsDeps=("idna" "certifi" "chardet" "urllib3" "requests")
 	gitprepare "YouCompleteMe" "third_party/" "${YouCompleteMe[@]}"
+	gitprepare "YouCompleteMe" "third_party/requests_deps/" "${YouCompleteMeRequestsDeps[@]}"
 
-	local ycmd=("bottle" "python-frozendict" "python-future" "waitress" "requests")
-
-	if [[ "$_gocode" == "y" ]]; then
-		ycmd+=("gocode" "godef")
-	fi
+	local ycmd=("bottle" "regex" "python-frozendict" "jedi" "parso" "python-future" "waitress" "requests")
 
 	if [[ "$_omnisharp" == "y" ]]; then
 		ycmd+=("OmniSharpServer")
@@ -186,8 +190,10 @@ prepare() {
 
 	gitprepare "YouCompleteMe/third_party/ycmd" "third_party/" "${ycmd[@]}"
 
-	local Jedi=("waitress" "jedi" "bottle" "parso")
-	gitprepare "YouCompleteMe/third_party/ycmd/third_party/jedi" "vendor/" "${Jedi[@]}"
+	if [[ "$_gocode" == "y" ]]; then
+                gitprepare "YouCompleteMe/third_party/ycmd/third_party/go/src/github.com/mdempsky" "" "gocode"
+                gitprepare "YouCompleteMe/third_party/ycmd/third_party/go/src/github.com/rogpeppe" "" "godef"
+	fi
 
 	if [[ "$_omnisharp" == "y" ]]; then
 		local OmniSharpServer=("NRefactory" "cecil")
@@ -262,14 +268,17 @@ package() {
 	fi
 
 	mkdir -p "$pkgdir/$vimfiles_dir/third_party/ycmd/third_party"
+	mkdir -p "$pkgdir/$vimfiles_dir/third_party/requests_deps"
 
 	cp -r "$srcdir/YouCompleteMe/"{autoload,doc,plugin,python} \
 		"$pkgdir/$vimfiles_dir"
-	cp -r "$srcdir/YouCompleteMe/third_party/"{pythonfutures,requests-futures} \
+	cp -r "$srcdir/YouCompleteMe/third_party/"{pythonfutures,requests-futures,python-future} \
 		"$pkgdir/$vimfiles_dir/third_party"
+	cp -r "$srcdir/YouCompleteMe/third_party/requests_deps/"{certifi,chardet,idna,requests,urllib3} \
+		"$pkgdir/$vimfiles_dir/third_party/requests_deps"
 	cp -r "$srcdir/YouCompleteMe/third_party/ycmd/"{ycmd,ycm_core.so,CORE_VERSION,clang_includes} \
 		"$pkgdir/$vimfiles_dir/third_party/ycmd"
-	cp -r "$srcdir/YouCompleteMe/third_party/ycmd/third_party/"{bottle,parso,frozendict,jedi,python-future,requests,waitress} \
+	cp -r "$srcdir/YouCompleteMe/third_party/ycmd/third_party/"{bottle,cregex,frozendict,jedi,parso,python-future,requests,waitress} \
 		"$pkgdir/$vimfiles_dir/third_party/ycmd/third_party"
 
 	if [[ "$_omnisharp" == "y" ]]; then
@@ -327,10 +336,11 @@ package() {
 	rm -r "$pkgdir/$vimfiles_dir/third_party/ycmd/third_party/python-future/docs"
 
 	# Finally compile all the python files to bytecode.
+        # not sure why this block causes the pkg function to fail unless you add "|| :"
 	if [[ "$_use_python2" == "ON" ]]; then
-		python2 -m compileall "$pkgdir"
+		python2 -m compileall "$pkgdir" || :
 	else
-		python3 -m compileall "$pkgdir"
+		python3 -m compileall "$pkgdir" || :
 	fi
 
 }
