version bump 5 commits vim-youcompleteme-git

diff --git a/vim-youcompleteme-git/PKGBUILD b/vim-youcompleteme-git/PKGBUILD
--- a/vim-youcompleteme-git/PKGBUILD
+++ b/vim-youcompleteme-git/PKGBUILD
@@ -46,7 +46,7 @@ _neovim="$NEOVIM_YOUCOMPLETEME"
 #                                    Default PKGBUILD Configuration                                       #
 #=========================================================================================================#
 pkgname=vim-youcompleteme-git
-pkgver=r2764.21f1cc57
+pkgver=r2769.604a2a02
 pkgver() {
   cd "YouCompleteMe" || exit
   printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
@@ -76,7 +76,7 @@ source=(
 'git+https://github.com/urllib3/urllib3.git'  #requests
 'git+https://github.com/bottlepy/bottle.git'  #ycmd
 'git+https://github.com/Pylons/waitress.git'              #ycmd,jediHTTP
-'git+https://github.com/ycm-core/regex.git'  #ycmd
+'git+https://bitbucket.org/mrabarnett/mrab-regex.git'
 'git+https://github.com/gorakhargosh/watchdog' 
 'git+https://github.com/gorakhargosh/pathtools' 
 'git+https://github.com/mitsuhiko/flask-sphinx-themes.git' 
@@ -216,7 +216,7 @@ prepare() {
   gitprepare "YouCompleteMe" "third_party/" "${YouCompleteMe[@]}"
   gitprepare "YouCompleteMe" "third_party/requests_deps/" "${YouCompleteMeRequestsDeps[@]}"
 
-  local ycmd=("bottle" "regex" "waitress")
+  local ycmd=("bottle" "mrab-regex" "waitress")
 
   gitprepare "YouCompleteMe/third_party/ycmd" "third_party/" "${ycmd[@]}"
 
@@ -252,16 +252,18 @@ build() {
   cmake -G "Unix Makefiles" -DUSE_PYTHON2=$_use_python2 -DUSE_SYSTEM_LIBCLANG="$_use_system_clang" . "$srcdir/YouCompleteMe/third_party/ycmd/cpp"
   make ycm_core
 
-  if [[ "$_use_system_python" == "n" ]]; then
-    mkdir -p "$srcdir/regex_build"
-    cd "$srcdir/regex_build" || exit
-    cmake -G "Unix Makefiles" -DUSE_PYTHON2=$_use_python2 -DUSE_SYSTEM_LIBCLANG="$_use_system_clang" . "$srcdir/YouCompleteMe/third_party/ycmd/third_party/cregex"
-    make _regex
-  fi
+  # if [[ "$_use_system_python" == "n" ]]; then
+    # mkdir -p "$srcdir/regex_build"
+    # cd "$srcdir/regex_build" || exit
+    # cmake -G "Unix Makefiles" -DUSE_PYTHON2=$_use_python2 -DUSE_SYSTEM_LIBCLANG="$_use_system_clang" . "$srcdir/YouCompleteMe/third_party/ycmd/third_party/mrab-regex"
+    # make _regex
+  # fi
 
   if [[ "$_use_system_python" == "n" ]]; then
     cd "$srcdir/YouCompleteMe/third_party/ycmd/third_party/watchdog_deps/watchdog" || { echo "cant cd to watchdog" ; exit ; }
     python setup.py build --build-base="build/3" --build-lib="build/lib3" || { echo "fail build watchdog" ; exit ; }
+    cd "$srcdir/YouCompleteMe/third_party/ycmd/third_party/mrab-regex" || { echo "cant cd to mrab-regex" ; exit ; }
+    python setup.py build --build-base="regex-build/3" --build-lib="regex-build" || { echo "fail build watchdog" ; exit ; }
   fi
 
   if [[ "$_rust" == "y" ]]; then
@@ -279,7 +281,7 @@ build() {
     msg2 'Building gopls for go completion...' # BuildGoCode()
     cd "$srcdir/YouCompleteMe/third_party/ycmd/third_party/go" || exit
     # find gopls version by grepping third_party/ycmd/build.py
-    go get golang.org/x/tools/gopls@v0.4.4
+    go get golang.org/x/tools/gopls@v0.5.1
   else
     msg2 'Skipping Gocode completer...'
   fi
@@ -358,7 +360,7 @@ package() {
     cp -r "$srcdir/YouCompleteMe/third_party/requests_deps/"{certifi,chardet,idna,requests,urllib3} \
       "$pkgdir/$vimfiles_dir/third_party/requests_deps"
 
-    cp -r "$srcdir/YouCompleteMe/third_party/ycmd/third_party/"{bottle,clang,cregex,waitress} \
+    cp -r "$srcdir/YouCompleteMe/third_party/ycmd/third_party/"{bottle,clang,mrab-regex,waitress} \
       "$pkgdir/$vimfiles_dir/third_party/ycmd/third_party"
     cp -r "$srcdir/YouCompleteMe/third_party/ycmd/third_party/requests_deps/"{certifi,chardet,idna,requests,urllib3} \
       "$pkgdir/$vimfiles_dir/third_party/ycmd/third_party/requests_deps"
